/**
 * Gera src/data/guitarDatabase.json (executar: node scripts/buildGuitarDatabase.cjs)
 */
const { writeFileSync } = require("fs");
const { join } = require("path");

/** @type {import('../src/types/guitarDatabase.ts').ScaleEntry[]} */
const scales = [
  {
    id: "scale_ionian",
    name: "Ionian",
    namePt: "Jônio (escala maior)",
    family: "major",
    intervalsSemitones: [0, 2, 4, 5, 7, 9, 11],
    intervalSymbols: ["P1", "M2", "M3", "P4", "P5", "M6", "M7"],
    notesWithRootC: ["C", "D", "E", "F", "G", "A", "B"],
    degreeCount: 7,
  },
  {
    id: "scale_dorian",
    name: "Dorian",
    namePt: "Dórico",
    family: "mode_dorian",
    intervalsSemitones: [0, 2, 3, 5, 7, 9, 10],
    intervalSymbols: ["P1", "M2", "m3", "P4", "P5", "M6", "m7"],
    notesWithRootC: ["C", "D", "Eb", "F", "G", "A", "Bb"],
    degreeCount: 7,
  },
  {
    id: "scale_phrygian",
    name: "Phrygian",
    namePt: "Frígio",
    family: "mode_phrygian",
    intervalsSemitones: [0, 1, 3, 5, 7, 8, 10],
    intervalSymbols: ["P1", "m2", "m3", "P4", "P5", "m6", "m7"],
    notesWithRootC: ["C", "Db", "Eb", "F", "G", "Ab", "Bb"],
    degreeCount: 7,
  },
  {
    id: "scale_lydian",
    name: "Lydian",
    namePt: "Lídio",
    family: "mode_lydian",
    intervalsSemitones: [0, 2, 4, 6, 7, 9, 11],
    intervalSymbols: ["P1", "M2", "M3", "A4", "P5", "M6", "M7"],
    notesWithRootC: ["C", "D", "E", "F#", "G", "A", "B"],
    degreeCount: 7,
  },
  {
    id: "scale_mixolydian",
    name: "Mixolydian",
    namePt: "Mixolídio",
    family: "mode_mixolydian",
    intervalsSemitones: [0, 2, 4, 5, 7, 9, 10],
    intervalSymbols: ["P1", "M2", "M3", "P4", "P5", "M6", "m7"],
    notesWithRootC: ["C", "D", "E", "F", "G", "A", "Bb"],
    degreeCount: 7,
  },
  {
    id: "scale_aeolian",
    name: "Aeolian",
    namePt: "Eólio (menor natural)",
    family: "minor_natural",
    intervalsSemitones: [0, 2, 3, 5, 7, 8, 10],
    intervalSymbols: ["P1", "M2", "m3", "P4", "P5", "m6", "m7"],
    notesWithRootC: ["C", "D", "Eb", "F", "G", "Ab", "Bb"],
    degreeCount: 7,
  },
  {
    id: "scale_locrian",
    name: "Locrian",
    namePt: "Lócrio",
    family: "mode_locrian",
    intervalsSemitones: [0, 1, 3, 5, 6, 8, 10],
    intervalSymbols: ["P1", "m2", "m3", "P4", "d5", "m6", "m7"],
    notesWithRootC: ["C", "Db", "Eb", "F", "Gb", "Ab", "Bb"],
    degreeCount: 7,
  },
  {
    id: "scale_harmonic_minor",
    name: "Harmonic minor",
    namePt: "Menor harmônica",
    family: "minor_harmonic",
    intervalsSemitones: [0, 2, 3, 5, 7, 8, 11],
    intervalSymbols: ["P1", "M2", "m3", "P4", "P5", "m6", "M7"],
    notesWithRootC: ["C", "D", "Eb", "F", "G", "Ab", "B"],
    degreeCount: 7,
  },
  {
    id: "scale_melodic_minor",
    name: "Melodic minor (jazz)",
    namePt: "Menor melódica (jazz)",
    family: "minor_melodic",
    intervalsSemitones: [0, 2, 3, 5, 7, 9, 11],
    intervalSymbols: ["P1", "M2", "m3", "P4", "P5", "M6", "M7"],
    notesWithRootC: ["C", "D", "Eb", "F", "G", "A", "B"],
    degreeCount: 7,
  },
  {
    id: "scale_pent_major",
    name: "Major pentatonic",
    namePt: "Pentatônica maior",
    family: "pentatonic_major",
    intervalsSemitones: [0, 2, 4, 7, 9],
    intervalSymbols: ["P1", "M2", "M3", "P5", "M6"],
    notesWithRootC: ["C", "D", "E", "G", "A"],
    degreeCount: 5,
  },
  {
    id: "scale_pent_minor",
    name: "Minor pentatonic",
    namePt: "Pentatônica menor",
    family: "pentatonic_minor",
    intervalsSemitones: [0, 3, 5, 7, 10],
    intervalSymbols: ["P1", "m3", "P4", "P5", "m7"],
    notesWithRootC: ["C", "Eb", "F", "G", "Bb"],
    degreeCount: 5,
  },
  {
    id: "scale_blues",
    name: "Blues",
    namePt: "Blues (hexatônica)",
    family: "blues",
    intervalsSemitones: [0, 3, 5, 6, 7, 10],
    intervalSymbols: ["P1", "m3", "P4", "TT", "P5", "m7"],
    notesWithRootC: ["C", "Eb", "F", "Gb", "G", "Bb"],
    degreeCount: 6,
  },
];

let voicingSerial = 0;
const V = (cagedForm, bassString, bassFret, frets, diagram, fingers) => ({
  id: `voicing_${String(++voicingSerial).padStart(4, "0")}`,
  cagedForm,
  bassString,
  bassFret,
  frets,
  diagram,
  ...(fingers ? { fingers } : {}),
});

/** @type {import('../src/types/guitarDatabase.ts').ChordEntry[]} */
const chords = [
  {
    id: "chord_C",
    symbol: "C",
    namePt: "Dó maior",
    quality: "major",
    referenceKey: "C",
    voicings: [V("C", 5, 3, [-1, 3, 2, 0, 1, 0], "x32010", [0, 3, 2, 0, 1, 0]), V("G", 6, 8, [8, 10, 10, 9, 8, 8], "8-10-10-9-8-8")],
  },
  {
    id: "chord_G",
    symbol: "G",
    namePt: "Sol maior",
    quality: "major",
    referenceKey: "G",
    voicings: [V("G", 6, 3, [3, 2, 0, 0, 0, 3], "320003"), V("E", 6, 3, [3, 2, 0, 0, 3, 3], "320033")],
  },
  {
    id: "chord_D",
    symbol: "D",
    namePt: "Ré maior",
    quality: "major",
    referenceKey: "D",
    voicings: [V("D", 4, 0, [-1, -1, 0, 2, 3, 2], "xx0232"), V("A", 5, 5, [-1, 5, 5, 7, 7, 5], "x55775")],
  },
  {
    id: "chord_A",
    symbol: "A",
    namePt: "Lá maior",
    quality: "major",
    referenceKey: "A",
    voicings: [V("A", 5, 0, [-1, 0, 2, 2, 2, 0], "x02220"), V("E", 5, 5, [5, 5, 7, 7, 7, 5], "557775")],
  },
  {
    id: "chord_E",
    symbol: "E",
    namePt: "Mi maior",
    quality: "major",
    referenceKey: "E",
    voicings: [V("E", 6, 0, [0, 2, 2, 1, 0, 0], "022100"), V("D", 4, 9, [-1, -1, 9, 9, 9, 12], "xx99912")],
  },
  {
    id: "chord_F",
    symbol: "F",
    namePt: "Fá maior",
    quality: "major",
    referenceKey: "F",
    voicings: [V("E", 6, 1, [1, 3, 3, 2, 1, 1], "133211"), V("D", 5, 8, [-1, 8, 10, 10, 10, 8], "x8101098")],
  },
  {
    id: "chord_Bb",
    symbol: "Bb",
    namePt: "Si bemol maior",
    quality: "major",
    referenceKey: "Bb",
    voicings: [V("A", 5, 1, [-1, 1, 3, 3, 3, 1], "x13331"), V("E", 6, 6, [6, 8, 8, 7, 6, 6], "688766")],
  },
  {
    id: "chord_B",
    symbol: "B",
    namePt: "Si maior",
    quality: "major",
    referenceKey: "B",
    voicings: [V("A", 5, 2, [-1, 2, 4, 4, 4, 2], "x24442"), V("E", 6, 7, [7, 9, 9, 8, 7, 7], "799877")],
  },
  {
    id: "chord_Am",
    symbol: "Am",
    namePt: "Lá menor",
    quality: "minor",
    referenceKey: "A",
    voicings: [V("A", 5, 0, [-1, 0, 2, 2, 1, 0], "x02210"), V("E", 5, 5, [5, 5, 7, 7, 5, 5], "557755")],
  },
  {
    id: "chord_Em",
    symbol: "Em",
    namePt: "Mi menor",
    quality: "minor",
    referenceKey: "E",
    voicings: [V("E", 6, 0, [0, 2, 2, 0, 0, 0], "022000"), V("D", 4, 7, [-1, -1, 9, 9, 8, 7], "xx9987")],
  },
  {
    id: "chord_Dm",
    symbol: "Dm",
    namePt: "Ré menor",
    quality: "minor",
    referenceKey: "D",
    voicings: [V("D", 4, 0, [-1, -1, 0, 2, 3, 1], "xx0231"), V("A", 5, 5, [-1, 5, 7, 7, 6, 5], "x57765")],
  },
  {
    id: "chord_Cm",
    symbol: "Cm",
    namePt: "Dó menor",
    quality: "minor",
    referenceKey: "C",
    voicings: [V("A", 5, 3, [-1, 3, 5, 5, 4, 3], "x35543"), V("E", 6, 8, [8, 10, 10, 8, 8, 8], "8101088")],
  },
  {
    id: "chord_Gm",
    symbol: "Gm",
    namePt: "Sol menor",
    quality: "minor",
    referenceKey: "G",
    voicings: [V("G", 6, 3, [3, 5, 5, 3, 3, 3], "355333"), V("D", 5, 10, [-1, 10, 12, 12, 11, 10], "x101211109")],
  },
  {
    id: "chord_Fm",
    symbol: "Fm",
    namePt: "Fá menor",
    quality: "minor",
    referenceKey: "F",
    voicings: [V("E", 6, 1, [1, 3, 3, 1, 1, 1], "133111"), V("A", 5, 8, [-1, 8, 10, 10, 9, 8], "x8101098")],
  },
  {
    id: "chord_C7",
    symbol: "C7",
    namePt: "Dó com sétima",
    quality: "dominant7",
    referenceKey: "C",
    voicings: [V("A", 5, 3, [-1, 3, 2, 3, 1, 0], "x32310"), V("E", 6, 8, [8, 10, 8, 9, 8, 8], "8108988")],
  },
  {
    id: "chord_G7",
    symbol: "G7",
    namePt: "Sol com sétima",
    quality: "dominant7",
    referenceKey: "G",
    voicings: [V("G", 6, 3, [3, 2, 0, 0, 0, 1], "320001"), V("D", 4, 3, [-1, -1, 5, 4, 3, 3], "xx5433")],
  },
  {
    id: "chord_D7",
    symbol: "D7",
    namePt: "Ré com sétima",
    quality: "dominant7",
    referenceKey: "D",
    voicings: [V("C", 4, 5, [-1, 5, 5, 5, 7, 5], "x55575"), V("A", 5, 5, [-1, 5, 7, 5, 7, 5], "x57575")],
  },
  {
    id: "chord_A7",
    symbol: "A7",
    namePt: "Lá com sétima",
    quality: "dominant7",
    referenceKey: "A",
    voicings: [V("A", 5, 0, [-1, 0, 2, 0, 2, 0], "x02020"), V("E", 5, 5, [5, 5, 7, 6, 7, 5], "557675")],
  },
  {
    id: "chord_E7",
    symbol: "E7",
    namePt: "Mi com sétima",
    quality: "dominant7",
    referenceKey: "E",
    voicings: [V("E", 6, 0, [0, 2, 0, 1, 0, 0], "020100"), V("A", 5, 7, [-1, 7, 9, 7, 9, 7], "x79797")],
  },
  {
    id: "chord_B7",
    symbol: "B7",
    namePt: "Si com sétima",
    quality: "dominant7",
    referenceKey: "B",
    voicings: [V("A", 5, 2, [-1, 2, 1, 2, 0, 2], "x21202"), V("E", 6, 7, [7, 9, 7, 8, 7, 7], "797877")],
  },
  {
    id: "chord_F7",
    symbol: "F7",
    namePt: "Fá com sétima",
    quality: "dominant7",
    referenceKey: "F",
    voicings: [V("E", 6, 1, [1, 3, 1, 2, 1, 1], "131211"), V("D", 5, 8, [-1, 8, 10, 8, 10, 8], "x8108108")],
  },
  {
    id: "chord_Cmaj7",
    symbol: "Cmaj7",
    namePt: "Dó maior com sétima maior",
    quality: "major7",
    referenceKey: "C",
    voicings: [V("C", 5, 3, [-1, 3, 2, 0, 0, 0], "x32000"), V("G", 6, 8, [8, 10, 9, 9, 8, 7], "8109987")],
  },
  {
    id: "chord_Gmaj7",
    symbol: "Gmaj7",
    namePt: "Sol maior com sétima maior",
    quality: "major7",
    referenceKey: "G",
    voicings: [V("G", 6, 3, [3, 2, 0, 0, 0, 2], "320002"), V("E", 6, 3, [3, 5, 4, 4, 3, 3], "354433")],
  },
  {
    id: "chord_Dmaj7",
    symbol: "Dmaj7",
    namePt: "Ré maior com sétima maior",
    quality: "major7",
    referenceKey: "D",
    voicings: [V("C", 4, 5, [-1, 5, 5, 5, 7, 7], "x55577"), V("A", 5, 5, [-1, 5, 7, 6, 7, 5], "x57675")],
  },
  {
    id: "chord_Amaj7",
    symbol: "Amaj7",
    namePt: "Lá maior com sétima maior",
    quality: "major7",
    referenceKey: "A",
    voicings: [V("A", 5, 0, [-1, 0, 2, 1, 2, 0], "x02120"), V("G", 4, 9, [-1, -1, 11, 10, 9, 9], "xx111099")],
  },
  {
    id: "chord_Fmaj7",
    symbol: "Fmaj7",
    namePt: "Fá maior com sétima maior",
    quality: "major7",
    referenceKey: "F",
    voicings: [V("E", 6, 1, [1, 3, 2, 2, 1, 1], "132211"), V("D", 5, 8, [-1, 8, 10, 9, 10, 8], "x8109108")],
  },
  {
    id: "chord_Am7",
    symbol: "Am7",
    namePt: "Lá menor com sétima",
    quality: "minor7",
    referenceKey: "A",
    voicings: [V("A", 5, 0, [-1, 0, 2, 0, 1, 0], "x02010"), V("D", 4, 5, [-1, -1, 7, 5, 5, 5], "xx7555")],
  },
  {
    id: "chord_Dm7",
    symbol: "Dm7",
    namePt: "Ré menor com sétima",
    quality: "minor7",
    referenceKey: "D",
    voicings: [V("A", 4, 5, [-1, 5, 5, 5, 6, 5], "x55565"), V("C", 4, 5, [-1, 5, 5, 5, 6, 5], "x55565")],
  },
  {
    id: "chord_Em7",
    symbol: "Em7",
    namePt: "Mi menor com sétima",
    quality: "minor7",
    referenceKey: "E",
    voicings: [V("E", 6, 0, [0, 2, 0, 0, 0, 0], "020000"), V("A", 5, 7, [-1, 7, 9, 7, 8, 7], "x79787")],
  },
  {
    id: "chord_Gm7",
    symbol: "Gm7",
    namePt: "Sol menor com sétima",
    quality: "minor7",
    referenceKey: "G",
    voicings: [V("G", 6, 3, [3, 5, 3, 3, 3, 3], "353333"), V("D", 5, 10, [-1, 10, 12, 10, 11, 10], "x101210119")],
  },
  {
    id: "chord_Bm7",
    symbol: "Bm7",
    namePt: "Si menor com sétima",
    quality: "minor7",
    referenceKey: "B",
    voicings: [V("A", 5, 2, [-1, 2, 4, 2, 3, 2], "x24232"), V("E", 6, 7, [7, 9, 7, 7, 7, 7], "797777")],
  },
  {
    id: "chord_Cm7",
    symbol: "Cm7",
    namePt: "Dó menor com sétima",
    quality: "minor7",
    referenceKey: "C",
    voicings: [V("A", 5, 3, [-1, 3, 5, 3, 4, 3], "x35343"), V("E", 6, 8, [8, 10, 8, 8, 8, 8], "8108888")],
  },
  {
    id: "chord_Fm7",
    symbol: "Fm7",
    namePt: "Fá menor com sétima",
    quality: "minor7",
    referenceKey: "F",
    voicings: [V("E", 6, 1, [1, 3, 1, 1, 1, 1], "131111"), V("A", 5, 8, [-1, 8, 10, 8, 9, 8], "x810898")],
  },
  {
    id: "chord_Bdim",
    symbol: "Bdim",
    namePt: "Si diminuto",
    quality: "diminished",
    referenceKey: "B",
    voicings: [V("A", 5, 2, [-1, 2, 3, 4, 3, -1], "x2343x"), V("D", 4, 4, [-1, -1, 4, 5, 4, 5], "xx4545")],
  },
  {
    id: "chord_Fsharp_dim",
    symbol: "F#dim",
    namePt: "Fá sustenido diminuto",
    quality: "diminished",
    referenceKey: "F#",
    voicings: [V("D", 4, 2, [-1, -1, 2, 3, 2, 3], "xx2323"), V("A", 5, 9, [-1, 9, 10, 11, 10, -1], "x9101110x")],
  },
  {
    id: "chord_Cdim",
    symbol: "Cdim",
    namePt: "Dó diminuto",
    quality: "diminished",
    referenceKey: "C",
    voicings: [V("A", 5, 3, [-1, 3, 4, 5, 4, -1], "x3454x"), V("E", 4, 8, [-1, -1, 8, 9, 8, 9], "xx8989")],
  },
  {
    id: "chord_Caug",
    symbol: "Caug",
    namePt: "Dó aumentado",
    quality: "augmented",
    referenceKey: "C",
    voicings: [V("G", 5, 4, [-1, -1, 5, 5, 5, 4], "xx5554"), V("A", 5, 3, [-1, 3, 2, 1, 1, 0], "x32110")],
  },
  {
    id: "chord_Csus2",
    symbol: "Csus2",
    namePt: "Dó sus2",
    quality: "sus2",
    referenceKey: "C",
    voicings: [V("D", 4, 3, [-1, -1, 5, 5, 3, 3], "xx5533"), V("G", 6, 8, [8, 10, 10, 10, 8, 8], "810101088")],
  },
  {
    id: "chord_Csus4",
    symbol: "Csus4",
    namePt: "Dó sus4",
    quality: "sus4",
    referenceKey: "C",
    voicings: [V("G", 5, 3, [-1, 3, 3, 0, 1, 1], "x33011"), V("A", 5, 8, [-1, 8, 10, 10, 11, 8], "x810118")],
  },
  {
    id: "chord_Gsus4",
    symbol: "Gsus4",
    namePt: "Sol sus4",
    quality: "sus4",
    referenceKey: "G",
    voicings: [V("G", 6, 3, [3, 2, 0, 0, 1, 3], "320013"), V("D", 4, 5, [-1, -1, 5, 5, 8, 8], "xx5588")],
  },
  {
    id: "chord_Asus4",
    symbol: "Asus4",
    namePt: "Lá sus4",
    quality: "sus4",
    referenceKey: "A",
    voicings: [V("A", 5, 0, [-1, 0, 2, 2, 3, 0], "x02230"), V("E", 5, 5, [5, 5, 7, 7, 8, 5], "557785")],
  },
  {
    id: "chord_Dsus2",
    symbol: "Dsus2",
    namePt: "Ré sus2",
    quality: "sus2",
    referenceKey: "D",
    voicings: [V("D", 4, 0, [-1, -1, 0, 2, 3, 0], "xx0230"), V("A", 5, 5, [-1, 5, 7, 7, 5, 5], "x57755")],
  },
  {
    id: "chord_Dsus4",
    symbol: "Dsus4",
    namePt: "Ré sus4",
    quality: "sus4",
    referenceKey: "D",
    voicings: [V("D", 4, 0, [-1, -1, 0, 2, 3, 3], "xx0233"), V("G", 6, 5, [5, 5, 7, 7, 8, 5], "557785")],
  },
  {
    id: "chord_Cadd9",
    symbol: "Cadd9",
    namePt: "Dó add9",
    quality: "add9",
    referenceKey: "C",
    voicings: [V("C", 5, 3, [-1, 3, 2, 0, 3, 0], "x32030"), V("G", 6, 8, [8, 10, 10, 9, 10, 8], "810109108")],
  },
  {
    id: "chord_Gadd9",
    symbol: "Gadd9",
    namePt: "Sol add9",
    quality: "add9",
    referenceKey: "G",
    voicings: [V("G", 6, 3, [3, 2, 0, 0, 0, 2], "320002"), V("A", 5, 10, [-1, 10, 9, 7, 7, 10], "x1097710")],
  },
  {
    id: "chord_Eadd9",
    symbol: "Eadd9",
    namePt: "Mi add9",
    quality: "add9",
    referenceKey: "E",
    voicings: [V("E", 6, 0, [0, 2, 4, 1, 0, 0], "024100"), V("D", 4, 9, [-1, -1, 9, 9, 9, 11], "xx99911")],
  },
  {
    id: "chord_C6",
    symbol: "C6",
    namePt: "Dó com sexta",
    quality: "sixth",
    referenceKey: "C",
    voicings: [V("C", 5, 3, [-1, 3, 2, 2, 1, 0], "x32210"), V("A", 5, 8, [-1, 8, 10, 9, 10, 8], "x8109108")],
  },
  {
    id: "chord_G6",
    symbol: "G6",
    namePt: "Sol com sexta",
    quality: "sixth",
    referenceKey: "G",
    voicings: [V("G", 6, 3, [3, 2, 0, 0, 0, 0], "320000"), V("D", 4, 5, [-1, -1, 5, 5, 5, 5], "xx5555")],
  },
  {
    id: "chord_C9",
    symbol: "C9",
    namePt: "Dó nona",
    quality: "ninth",
    referenceKey: "C",
    voicings: [V("C", 5, 3, [-1, 3, 2, 3, 3, 3], "x32333"), V("E", 6, 8, [8, 10, 8, 9, 10, 8], "81089108")],
  },
  {
    id: "chord_G9",
    symbol: "G9",
    namePt: "Sol nona",
    quality: "ninth",
    referenceKey: "G",
    voicings: [V("G", 6, 3, [3, 2, 0, 2, 0, 1], "320201"), V("A", 5, 10, [-1, 10, 9, 10, 10, 10], "x109101010")],
  },
];

/** Graus por tom maior (C, G, A, D) — símbolos usados nos padrões. */
const KEY_MAPS = {
  C: {
    I: "C",
    ii: "Dm",
    iii: "Em",
    IV: "F",
    V: "G",
    vi: "Am",
    bVII: "Bb",
    bVI: "Ab",
    bIII: "Eb",
    I7: "C7",
    IV7: "F7",
    V7: "G7",
    ii7: "Dm7",
    vi7: "Am7",
    IVmaj7: "Fmaj7",
    Vmaj7: "Gmaj7",
  },
  G: {
    I: "G",
    ii: "Am",
    iii: "Bm",
    IV: "C",
    V: "D",
    vi: "Em",
    bVII: "F",
    bVI: "Eb",
    bIII: "Bb",
    I7: "G7",
    IV7: "C7",
    V7: "D7",
    ii7: "Am7",
    vi7: "Em7",
    IVmaj7: "Cmaj7",
    Vmaj7: "Dmaj7",
  },
  A: {
    I: "A",
    ii: "Bm",
    iii: "C#m",
    IV: "D",
    V: "E",
    vi: "F#m",
    bVII: "G",
    bVI: "F",
    bIII: "C",
    I7: "A7",
    IV7: "D7",
    V7: "E7",
    ii7: "Bm7",
    vi7: "F#m7",
    IVmaj7: "Dmaj7",
    Vmaj7: "Emaj7",
  },
  D: {
    I: "D",
    ii: "Em",
    iii: "F#m",
    IV: "G",
    V: "A",
    vi: "Bm",
    bVII: "C",
    bVI: "Bb",
    bIII: "F",
    I7: "D7",
    IV7: "G7",
    V7: "A7",
    ii7: "Em7",
    vi7: "Bm7",
    IVmaj7: "Gmaj7",
    Vmaj7: "Amaj7",
  },
};

const KEYS = ["C", "G", "A", "D"];

const PATTERN_BANK = [
  {
    name: "I–IV–V–I (rock clássico)",
    namePt: "I–IV–V–I (rock clássico)",
    genre: "rock",
    romanOrFunctions: "I IV V I",
    nums: ["I", "IV", "V", "I"],
    reference: "Base do rock e blues maior",
    difficulty: 2,
    tags: ["rock", "triades"],
  },
  {
    name: "Axis progression",
    namePt: "Progressão Axis (I–V–vi–IV)",
    genre: "rock_blues",
    romanOrFunctions: "I V vi IV",
    nums: ["I", "V", "vi", "IV"],
    reference: "Muito comum em pop/rock",
    difficulty: 2,
    tags: ["pop-rock", "axis"],
  },
  {
    name: "vi–IV–I–V",
    namePt: "vi–IV–I–V (emo/pop rock)",
    genre: "rock",
    romanOrFunctions: "vi IV I V",
    nums: ["vi", "IV", "I", "V"],
    reference: "Progressão sensível / alternativa",
    difficulty: 3,
    tags: ["rock", "emotional"],
  },
  {
    name: "I–bVII–IV (Mixolydian rock)",
    namePt: "I–bVII–IV (rock mixolídio)",
    genre: "rock",
    romanOrFunctions: "I bVII IV",
    nums: ["I", "bVII", "IV"],
    reference: "Clássica em riffs de hard rock",
    difficulty: 3,
    tags: ["rock", "mixolydian"],
  },
  {
    name: "I–bVII–I–IV",
    namePt: "I–bVII–I–IV",
    genre: "rock",
    romanOrFunctions: "I bVII I IV",
    nums: ["I", "bVII", "I", "IV"],
    reference: "Riff rock / southern rock",
    difficulty: 3,
    tags: ["rock", "riff"],
  },
  {
    name: "I–IV–bVII–IV",
    namePt: "I–IV–bVII–IV",
    genre: "rock",
    romanOrFunctions: "I IV bVII IV",
    nums: ["I", "IV", "bVII", "IV"],
    reference: "Cadência com modal interchange",
    difficulty: 3,
    tags: ["rock", "borrowed"],
  },
  {
    name: "I–V–IV–V",
    namePt: "I–V–IV–V",
    genre: "rock",
    romanOrFunctions: "I V IV V",
    nums: ["I", "V", "IV", "V"],
    reference: "Rock simples / punk",
    difficulty: 2,
    tags: ["rock", "punk"],
  },
  {
    name: "IV–I–V–I",
    namePt: "IV–I–V–I",
    genre: "rock",
    romanOrFunctions: "IV I V I",
    nums: ["IV", "I", "V", "I"],
    reference: "Ênfase no subdominante",
    difficulty: 2,
    tags: ["rock"],
  },
  {
    name: "V–IV–I (rock cadence)",
    namePt: "V–IV–I",
    genre: "rock",
    romanOrFunctions: "V IV I",
    nums: ["V", "IV", "I"],
    reference: "Cadência plagal invertida / rock",
    difficulty: 3,
    tags: ["rock", "cadence"],
  },
  {
    name: "I–vi–ii–V (turnaround)",
    namePt: "I–vi–ii–V (turnaround maior)",
    genre: "rock_blues",
    romanOrFunctions: "I vi ii V",
    nums: ["I", "vi", "ii", "V"],
    reference: "Jazz / rockabilly / pop sofisticado",
    difficulty: 4,
    tags: ["turnaround", "jazz-rock"],
  },
  {
    name: "ii–V–I",
    namePt: "ii–V–I",
    genre: "rock_blues",
    romanOrFunctions: "ii V I",
    nums: ["ii", "V", "I"],
    reference: "Cadência jazz aplicada ao rock",
    difficulty: 4,
    tags: ["jazz", "cadence"],
  },
  {
    name: "I–IV–V7–I",
    namePt: "I–IV–V7–I (blues rock maior)",
    genre: "rock_blues",
    romanOrFunctions: "I IV V7 I",
    nums: ["I", "IV", "V7", "I"],
    reference: "Blues maior / rock and roll",
    difficulty: 2,
    tags: ["blues-rock", "dominant"],
  },
  {
    name: "I–IV–I–V",
    namePt: "I–IV–I–V",
    genre: "rock",
    romanOrFunctions: "I IV I V",
    nums: ["I", "IV", "I", "V"],
    reference: "Rock clássico em 4 acordes",
    difficulty: 2,
    tags: ["rock"],
  },
  {
    name: "I–iii–IV–V",
    namePt: "I–iii–IV–V",
    genre: "rock",
    romanOrFunctions: "I iii IV V",
    nums: ["I", "iii", "IV", "V"],
    reference: "Variação com mediana",
    difficulty: 3,
    tags: ["rock"],
  },
  {
    name: "I–vi–IV–V (doo-wop)",
    namePt: "I–vi–IV–V (doo-wop / oldies)",
    genre: "rock_blues",
    romanOrFunctions: "I vi IV V",
    nums: ["I", "vi", "IV", "V"],
    reference: "Base do rock dos anos 50–60",
    difficulty: 2,
    tags: ["oldies", "doo-wop"],
  },
  {
    name: "I–bVI–bVII–I",
    namePt: "I–bVI–bVII–I (rock épico)",
    genre: "rock",
    romanOrFunctions: "I bVI bVII I",
    nums: ["I", "bVI", "bVII", "I"],
    reference: "Intercâmbio modal / arena rock",
    difficulty: 3,
    tags: ["rock", "epic"],
  },
  {
    name: "I–IV–bVI–V",
    namePt: "I–IV–bVI–V",
    genre: "rock",
    romanOrFunctions: "I IV bVI V",
    nums: ["I", "IV", "bVI", "V"],
    reference: "Pop rock com submediante bemol",
    difficulty: 3,
    tags: ["rock", "borrowed"],
  },
  {
    name: "I–V–vi–iii–IV–I–IV–V (canon pop)",
    namePt: "I–V–vi–iii–IV–I–IV–V (canon pop)",
    genre: "rock",
    romanOrFunctions: "I V vi iii IV I IV V",
    nums: ["I", "V", "vi", "iii", "IV", "I", "IV", "V"],
    reference: "Padrão harmônico muito usado em hits",
    difficulty: 4,
    tags: ["pop", "progression"],
  },
  {
    name: "I–ii–IV–V",
    namePt: "I–ii–IV–V",
    genre: "rock",
    romanOrFunctions: "I ii IV V",
    nums: ["I", "ii", "IV", "V"],
    reference: "Rock com acorde II menor",
    difficulty: 3,
    tags: ["rock"],
  },
  {
    name: "I–IV–vi–V",
    namePt: "I–IV–vi–V",
    genre: "rock",
    romanOrFunctions: "I IV vi V",
    nums: ["I", "IV", "vi", "V"],
    reference: "Variação do eixo harmônico",
    difficulty: 2,
    tags: ["rock"],
  },
  {
    name: "12-bar blues (quick IV)",
    namePt: "Blues de 12 compassos (quick IV)",
    genre: "blues",
    romanOrFunctions: "I7 I7 I7 I7 IV7 IV7 I7 I7 V7 IV7 I7 V7",
    nums: ["I7", "I7", "I7", "I7", "IV7", "IV7", "I7", "I7", "V7", "IV7", "I7", "V7"],
    reference: "Chicago / Texas blues",
    difficulty: 3,
    tags: ["12-bar", "blues", "dominant"],
  },
  {
    name: "12-bar blues (slow IV)",
    namePt: "Blues de 12 compassos (IV lento)",
    genre: "blues",
    romanOrFunctions: "I7 I7 I7 I7 IV7 IV7 I7 I7 V7 V7 I7 I7",
    nums: ["I7", "I7", "I7", "I7", "IV7", "IV7", "I7", "I7", "V7", "V7", "I7", "I7"],
    reference: "Variação com mais tempo no V7",
    difficulty: 3,
    tags: ["12-bar", "blues"],
  },
  {
    name: "8-bar blues (V–IV–I)",
    namePt: "Blues de 8 compassos (típico)",
    genre: "blues",
    romanOrFunctions: "I7 I7 I7 I7 IV7 IV7 V7 IV7",
    nums: ["I7", "I7", "I7", "I7", "IV7", "IV7", "V7", "IV7"],
    reference: "Blues de 8 compassos",
    difficulty: 3,
    tags: ["8-bar", "blues"],
  },
  {
    name: "Shuffle I7–IV7–I7–V7",
    namePt: "Shuffle I7–IV7–I7–V7",
    genre: "blues",
    romanOrFunctions: "I7 IV7 I7 V7",
    nums: ["I7", "IV7", "I7", "V7"],
    reference: "Blues shuffle de 4 acordes",
    difficulty: 2,
    tags: ["blues", "shuffle"],
  },
  {
    name: "Minor blues (i7–iv7–V7)",
    namePt: "Blues menor (i7–iv7–V7)",
    genre: "blues",
    romanOrFunctions: "i7 iv7 V7 i7",
    nums: ["i7", "iv7", "V7", "i7"],
    reference: "Blues menor (estrutura simplificada)",
    difficulty: 4,
    tags: ["blues", "minor"],
  },
];

/** Graus menores relativos ao modo (para padrão menor). */
const MINOR_MAPS = {
  C: { i7: "Cm7", iv7: "Fm7", V7: "G7" },
  G: { i7: "Gm7", iv7: "Cm7", V7: "D7" },
  A: { i7: "Am7", iv7: "Dm7", V7: "E7" },
  D: { i7: "Dm7", iv7: "Gm7", V7: "A7" },
};

function resolveDegree(key, deg) {
  const m = KEY_MAPS[key];
  if (deg === "bVII") return m.bVII;
  if (deg === "bVI") return m.bVI;
  if (deg === "bIII") return m.bIII;
  if (deg === "V7") return m.V7;
  if (deg === "IV7") return m.IV7;
  if (deg === "I7") return m.I7;
  if (deg === "ii7") return m.ii7;
  if (deg === "vi7") return m.vi7;
  if (deg === "IVmaj7") return m.IVmaj7;
  if (deg === "Vmaj7") return m.Vmaj7;
  if (deg === "i7") return MINOR_MAPS[key].i7;
  if (deg === "iv7") return MINOR_MAPS[key].iv7;
  return m[deg];
}

const progressions = [];
let pid = 1;

for (const pat of PATTERN_BANK) {
  for (const key of KEYS) {
    const chordList = pat.nums.map((d) => resolveDegree(key, d));
    progressions.push({
      id: `prog_${String(pid++).padStart(3, "0")}`,
      name: pat.name,
      namePt: pat.namePt,
      genre: pat.genre,
      keyExample: key,
      chords: chordList,
      romanOrFunctions: pat.romanOrFunctions,
      reference: pat.reference,
      difficulty: /** @type {const} */ (pat.difficulty),
      tags: pat.tags,
    });
    if (progressions.length >= 100) break;
  }
  if (progressions.length >= 100) break;
}

while (progressions.length < 100) {
  const key = KEYS[progressions.length % 4];
  const m = KEY_MAPS[key];
  progressions.push({
    id: `prog_${String(progressions.length + 1).padStart(3, "0")}`,
    name: "I–IV–V (fallback)",
    namePt: "I–IV–V (fallback)",
    genre: "rock",
    keyExample: key,
    chords: [m.I, m.IV, m.V],
    romanOrFunctions: "I IV V",
    reference: "Preenchimento harmônico",
    difficulty: 1,
    tags: ["rock", "triades"],
  });
}

const out = {
  version: 1,
  scales,
  chords,
  progressions: progressions.slice(0, 100),
};

const outPath = join(__dirname, "..", "src", "data", "guitarDatabase.json");
writeFileSync(outPath, JSON.stringify(out, null, 2), "utf8");
console.log("Wrote", outPath, "scales:", scales.length, "chords:", chords.length, "progressions:", out.progressions.length);
